<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IT9VA0I" failures="1" tests="4" name="ThreeTest" time="19.8" errors="0" timestamp="2022-09-02T04:21:29 IST">
  <testcase classname="tests.OneTest" name="testOne" time="16.841"/>
  <testcase classname="tests.LoginTest" name="login" time="1.339"/>
  <testcase classname="tests.TwoTest" name="testTwo" time="19.247"/>
  <testcase classname="tests.ThreeTest" name="testThree" time="19.372">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.ThreeTest.testThree(ThreeTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- ThreeTest -->
